config/routes.rb
Rails.application.routes.draw do
  	root to: 'home#index'

	devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

	resources :users, only: [:index] do
	  resources :profiles, only: [:show, :edit, :update]
	end

	resources :articles do
	  resources :comments
	end

	# no routes and more
	match "*path", "/", to: "restricts#routes_not_exists", via: :all
end

app/views/shared/_current_user.html.erb
<% if user_signed_in? %>
  <div class="clearfix">
    <span class="float-left">
      Hi <%= current_user.name.capitalize %>
    </span>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% if flash[:alert].present? %>
	<ul class="nav">
	  	<li class="nav-item">
	  		<div class="alert alert-danger mt-10" role="alert">
	    		<%= flash[:alert] %>
	  		</div>
		</li>
	</ul>
<% elsif flash[:alert].present? %>
	<ul class="nav">
		<li class="nav-item">
	  		<div class="alert alert-success mt-20" role="alert">
	    		<%= flash[:notice] %>
	  		</div>
		</li>
	</ul>
<% end %>

app/views/shared/_nav.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to 'Home', root_path, class: "nav-link" unless current_page?(root_path) %>
  </li>
  <% if user_signed_in? %>
    <!-- START post login block -->
    <li class="nav-item">
      <%= link_to 'Logout', destroy_user_session_path, class: "nav-link", method: :delete %>
    </li>
    <li class="nav-item">
      <%= link_to 'Profile', user_profile_path(current_user, current_user.profile), class: "nav-link" unless current_page?(user_profile_path(current_user, current_user.profile)) %>
    </li>
    <li class="nav-item">
      <%= link_to 'Users', users_path, class: "nav-link" if current_user.admin? %>
    </li>

    <li class="nav-item">
      <%= link_to 'Articles', articles_path, class: "nav-link" %>
    </li>
    <!-- END post login block -->
  <% else %>
    <!-- START pre login block -->
    <li class="nav-item">
      <%= link_to 'Login', new_user_session_path, class: "nav-link" unless current_page?(new_user_session_path) %>
    </li>
    <li class="nav-item">
      <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" unless current_page?(new_user_registration_path) %>
    </li>
    <!-- END pre login block -->
  <% end %>
</ul>